language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

before_install:
- git fetch --unshallow

install:
  - travis_retry pip install pybuilder coveralls
  - travis_retry pyb install_dependencies

env:
  PYTHONIOENCODING=UTF-8

script:
    - pyb -X analyze package run_cram_tests

after_success:
  - coveralls --verbose

before_deploy:
- pyb -v -X package

deploy:
  provider: pypi
  user: Immobilienscout24
  distributions: sdist
  skip_cleanup: true
  password:
    secure: Ai0ijkikrB8X4iyJr4i6yyoIDkccolksdyfaZdE5brpEVoYnUfJJ7b8e5j4lRKtscqMEzGSOV3zAu3t8M5/fGaGniSwVYahMXAvGsJtUlyzor9Nemo1h6wxSoM43p/EOa0XphqnNZfTzsT+d9SMF3pX65kejypM2i09Yrc5lITwPer05+CgHhSoKAF5L+p8mSjW9Tu7La8bt8RjKnvQ5OC98lzeepkgZBltGZt8AApVLnOD4FZN7lGZGj0vNMsf4zMqGPw1F5VPZ6qHYon2Wy8T4zPfktqqCupBcqbFwGCbhTwa+zB8W21zPXJFs8Sln57OWC1z+4F5UommxuWuKxKq2d5tzCir1ovVxozuNW2SYpONXZ/NDlb+e1FFBpLIFHh+4w1B1jfICiJVlsS4axTULRH/myc3PGLa9oLgIoFmBkIvatwHVJrhyhXdAlpWY202CHHGwmfKqaMwLlQgzJAowb7nAGoDIbn0hgLVXb9bjqfWR3YZQf8QHHVwTfs4HhU4hKgHLx8ooW3H1iko7/EkTLXhiTmo+k6yHrhPxuhrx9/7+G/73Iq5l//x0PjbqLZNzCUZHiWkvrAO1yB5qWeJnODBeGuPLOLcvjPtJvwHhtzvU8dnP0jOxPnDKLSXWA81GpGzh8iZRl/512oWDFMDEj70KoyrPJDHK3O8zX8E=
  on:
    repo: ImmobilienScout24/aws-certificate-management
    python: '2.7'
branch: master
